.TH "src/RInside.h" 3 "20 Dec 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RInside.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <R.h>\fP
.br
\fC#include <Rembedded.h>\fP
.br
\fC#include <Rversion.h>\fP
.br
\fC#include <Rdefines.h>\fP
.br
\fC#include <Rinterface.h>\fP
.br
\fC#include <R_ext/Parse.h>\fP
.br
\fC#include 'MemBuf.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRInside\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBR_INTERFACE_PTRS\fP"
.br
.ti -1c
.RI "#define \fBlogTxt\fP(x, b)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlogTxtFunction\fP (const char *file, const char *line, const char *expression, const bool \fBverbose\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define logTxt(x, b)"
.PP
Definition at line 56 of file RInside.h.
.PP
Referenced by RInside::RInside(), and RInside::~RInside().
.SS "#define R_INTERFACE_PTRS"
.PP
Definition at line 16 of file RInside.h.
.SH "Function Documentation"
.PP 
.SS "void logTxtFunction (const char * file, const char * line, const char * expression, const bool verbose)\fC [inline]\fP"
.PP
Definition at line 49 of file RInside.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
