.TH "src/RInsideEnvVars.h" 3 "20 Dec 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RInsideEnvVars.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBR_VARS\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* \fBR_VARS\fP[]"
.PP
Definition at line 1 of file RInsideEnvVars.h.
.PP
Referenced by RInside::RInside().
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
