.TH "src/setenv.c" 3 "20 Dec 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/setenv.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetenv\fP (const char *env_var, const char *env_val, int dummy)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int setenv (const char * env_var, const char * env_val, int dummy)"
.PP
Definition at line 13 of file setenv.c.
.PP
Referenced by RInside::init_tempdir(), and RInside::RInside().
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
